name: Deploy Cloudflare Worker

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node + Wrangler
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install -g wrangler@4   # v4 系

      # --- Secret を .dev.vars に書く（オプション）---
      - name: Write secrets for wrangler
        run: |
          echo "SLACK_BOT_TOKEN=${{ secrets.SLACK_BOT_TOKEN }}"     >> .dev.vars
          echo "SLACK_SIGNING_SECRET=${{ secrets.SLACK_SIGNING_SECRET }}" >> .dev.vars
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}"       >> .dev.vars
          echo "SCRAPBOX_COOKIE=${{ secrets.SCRAPBOX_COOKIE }}"     >> .dev.vars
        working-directory: your-worker

      - name: Deploy Worker
        run: wrangler deploy --minify
        working-directory: your-worker
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
